# Generated by Django 6.1.1 on 2026-09-23 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('company_profile', models.TextField(blank=True, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('required_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('required_education', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('function_field', models.CharField(blank=True, max_length=255, null=True)),
                ('telecommuting', models.BooleanField(default=False)),
                ('has_company_logo', models.BooleanField(default=False)),
                ('has_questions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
