# Generated by Django 6.1.1 on 2026-09-23 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredibilityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_json', models.JSONField()),
                ('indicator_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credibility_analyses', to='advertisements.advertisement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('training_dataset', models.CharField(blank=True, max_length=500, null=True)),
                ('metrics_json', models.JSONField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('model_name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=100)),
                ('predicted_class', models.CharField(choices=[('Potentially Legitimate', 'Potentially Legitimate'), ('Potentially Fraudulent', 'Potentially Fraudulent'), ('Requires Review', 'Requires Review')], max_length=32)),
                ('fraud_probability', models.FloatField()),
                ('confidence', models.FloatField()),
                ('uncertainty', models.FloatField(blank=True, null=True)),
                ('defer_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='advertisements.advertisement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_json', models.JSONField()),
                ('evidence_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='detection.prediction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
